Locked npm version in the Dockerfile - Closes #491
LiskHQ/lisk-explorer pull request #519
Opened 2018-04-04 15:37 UTC by MichalTuleja

Current update forces Docker build container to use npm version 5.7.1
### Review checklist
- The PR solves #491
- All new code follows best practices

2018-04-06 08:26 UTC, fchavant commented
@MichalTuleja `npm` comes from the official `node` image (first line of the `Dockerfile`) -- have you tried pulling the newest version?

2018-04-06 08:29 UTC, MichalTuleja commented
I'd rather stay with the version of Node that we support.
The upgrade of npm is justified by the latest Snyk report.

2018-04-06 08:33 UTC, ghost requested changes

2018-04-06 08:33 UTC, fchavant commented on Dockerfile
> +RUN npm install -g npm@5.7.1
Let's move this up to line 8 instead of having it in its own layer.

2018-04-09 10:15 UTC, ghost approved these changes

2018-04-09 10:15 UTC, ghost requested changes

2018-04-09 10:15 UTC, fchavant commented on Dockerfile
> +    npm install -g npm@5.7.1 \
`&&` missing

2018-04-09 16:24 UTC, ghost approved these changes

2018-04-09 16:28 UTC, merged